config/routes.rb
Rails.application.routes.draw do
  get 'pages/x'

  root 'pages#x'

  post 'pages/guardar'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def x

  end

  def guardar
  	puts params[:nombre]
  	puts params[:email]
  	puts params[:edad]
  	User.create(nombre: params[:nombre], edad: params[:edad], email: params[:email] )
 	redirect_to pages_x_path, notice: "registro guardado exitosamente"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taller</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/x.html.erb
<div class="jumbotron">
	<h1>Pagina de inicio</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel aliquam deleniti debitis nihil molestiae velit hic possimus exercitationem neque, sapiente nulla temporibus aliquid, adipisci quis numquam laborum reprehenderit repellat fugit.</p>
</div>

<h1>Franisco Javier García Mello</h1>
<br>
<h1>Formulario</h1>
<p> <%=	flash[:notice]%></p>
<form action="<%= pages_guardar_path %>" method="POST">
	<%= hidden_field_tag :authenticity_token,
		form_authenticity_token %>
	<label>Nombre</label>
	<input type="input" name="nombre">
	<br>
	<label>Email</label>
	<input type="input" name="email">
	<br>
	<label> Edad</label>
	<input type="input" name="edad">
	<br>
	<input type="submit" name="enviar">	


</form>